apiVersion: v1
kind: Pod
metadata:
  name: meupod  
spec:
  containers:
  - name: site
    image: lucasratzz/conversao-temperatura:v1 
    resources:
      requests:
        cpu: 50m
        memory: 64Mi
      limits:
        cpu: 200m
        memory: 1Gi                              
    ports:
      - containerPort: 8080
